updated the prerequisites in the getting started section
shipwright-io/website pull request #101
Opened 2023-08-16 11:17 UTC by ayushsatyam146

# Changes

Updated the prerequisites in the getting started section. Changed the installation URLs to use v0.11.0 and added tekton as a prerequisite.

# Submitter Checklist
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

2023-08-16 12:35 UTC, rolfedh reviewed
Nice work, Ayush! I've contributed some style suggestions including some short explanations. Please let me know if you have questions or if there's any more I can do to help.

2023-08-21 19:07 UTC, coreydaley requested changes

2023-08-21 19:07 UTC, coreydaley commented on content/en/docs/getting-started/installation.md
> +$ kubectl apply -f https://github.com/shipwright-io/build/releases/download/v0.11.0/release.yaml
```suggestion
$ kubectl apply -f https://github.com/shipwright-io/build/releases/latest/download/release.yaml
```

2023-08-21 19:07 UTC, coreydaley commented on content/en/docs/getting-started/installation.md
> +$ kubectl apply -f https://github.com/shipwright-io/build/releases/download/v0.11.0/sample-strategies.yaml
```suggestion
$ kubectl apply -f https://github.com/shipwright-io/build/releases/latest/download/sample-strategies.yaml
```

2023-08-21 19:07 UTC, coreydaley commented on content/en/docs/getting-started/installation.md
> +  kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.44.0/release.yaml
```suggestion
  kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
```

2023-09-04 13:19 UTC, qu1queee approved these changes
/approve

2023-09-04 13:23 UTC, merged