Fix broken links for shipwright-io/build references
shipwright-io/website pull request #115
Opened 2024-05-24 07:29 UTC by apoorvajagtap

# Changes

The buildstrategies.md references multiple examples of [build/samples/v1beta1](https://github.com/shipwright-io/build/tree/main/samples/v1beta1) directory. This PR copies the contents from the [build/samples](https://github.com/shipwright-io/build/tree/main/samples/v1beta1) to the current project. This would aid the manual syncs (until we automate) in case of any new changes instead of updating the multiple links each time.

Follow up of #113 

-->

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

2024-05-24 07:31 UTC, apoorvajagtap commented
/assign @adambkaplan

2024-05-24 07:31 UTC, apoorvajagtap commented
/kind documentation

2024-05-29 17:10 UTC, avinal requested changes
I see there are two types of changes, one for the broken links and the other is newly added YAMLs. 

I would suggest breaking it into at least two commits clearly showing the specific change. Rest looks good to me.

2024-08-12 12:55 UTC, apoorvajagtap commented
> I see there are two types of changes, one for the broken links and the other is newly added YAMLs.
> 
> I would suggest breaking it into at least two commits clearly showing the specific change. Rest looks good to me.

@avinal actually the addition of samples/ is done with the same intention of fixing the broken links (for example: https://github.com/shipwright-io/website/blob/main/content/en/docs/build/buildstrategies.md).

2024-09-02 13:09 UTC, apoorvajagtap commented
I just realised, that the tests have been failing since my last push. I am currently working on it & shall push the changes soon.

2024-09-13 18:43 UTC, adambkaplan commented
Blocked by #127

2024-09-13 18:46 UTC, adambkaplan requested changes

2024-09-13 18:46 UTC, adambkaplan commented on themes/docsy
@apoorvajagtap is there a reason why `docsy` is being updated here?

I also see a lot of other changes that go well beyond the scope of "fixing broken links" - can you explain this further in the body of your commit message?

2024-09-16 09:33 UTC, avinal commented on themes/docsy
+1, docsy changes should be moved to a separate PR.

2024-12-12 15:56 UTC, closed without merging

2024-12-12 15:56 UTC, adambkaplan commented
Looks like we incorporated these items in #140 - thanks for the contribution!