Add blog for vulnerability scanning in shipwright
shipwright-io/website pull request #123
Opened 2024-07-14 20:21 UTC by karanibm6

# Changes

- Add blog for vulnerability scanning in shipwright

# Submitter Checklist
- [ ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [ ] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Add blog for vulnerability scanning in shipwright
```

2024-07-14 20:21 UTC, karanibm6 commented
/kind blog

2024-07-15 14:13 UTC, adambkaplan approved these changes
/approve

I may need to re-kick the deploy preview later today to see the post. Alternatively, @karanibm6 you can set the timestamp to midnight UTC and the post should render in the preview.

2024-07-15 14:13 UTC, adambkaplan commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +date: 2024-07-15T14:20:01-04:00
Something to note - the deploy preview won't show the blog post if the post date is in the future.

2024-07-16 07:18 UTC, qu1queee requested changes
Amazing post! I enjoyed reading it!

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +There are many popular tools available for vulnerability scanning of container images, such as Clair, Trivy, Aqua Security, and Snyk. In Shipwright, we use Trivy under the covers for vulnerability sc
```suggestion
There are many popular tools available for vulnerability scanning of container images, such as Clair, Trivy, Aqua Security, and Snyk. 

In Shipwright, we use Trivy under the covers for vulnerability scanning, our rational for choosing this tool can be found in our [SHIP-0033](https://github.com/shipwright-io/community/blob/main/ships/0033-build-output-vulnerability-scanning.md).
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +Before we dive in how it works, lets explore the options offered by shipwright for vulnerability scanning of container builds :
```suggestion
Before we dive in how it works, lets explore the features offered by Shipwright for vulnerability scanning of container builds :
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +- vulnerabilityScan.enabled - Specify whether to run vulnerability scan for image. The supported values are true and false.
```suggestion
- `vulnerabilityScan.enabled`:  Specify whether to run vulnerability scan for image. The supported values are true and false.
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +- vulnerabilityScan.failOnFinding - indicates whether to fail the build run if the vulnerability scan results in vulnerabilities. The supported values are true and false. This field is optional and f
```suggestion
- `vulnerabilityScan.failOnFinding`: Indicates whether to fail the build run if the vulnerability scan results in vulnerabilities. The supported values are true and false. This field is optional and false by default.
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +- vulnerabilityScan.ignore.issues - references the security issues to be ignored in vulnerability scan
```suggestion
- `vulnerabilityScan.ignore.issues`:  References the security issues to be ignored in vulnerability scan
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +- vulnerabilityScan.ignore.severity - denotes the severity levels of security issues to be ignored, valid values are :
```suggestion
- `vulnerabilityScan.ignore.severity`: Denotes the severity levels of security issues to be ignored, valid values are :
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +- vulnerabilityScan.ignore.unfixed - indicates to ignore vulnerabilities for which no fix exists. The supported types are true and false.
```suggestion
- `vulnerabilityScan.ignore.unfixed`: Indicates to ignore vulnerabilities for which no fix exists. The supported types are true and false.
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +If you want to try out in kind cluster, follow the steps from [this](https://github.com/shipwright-io/build?tab=readme-ov-file#try-it) section till you create the push secret.
```suggestion
If you want to try out in kind cluster, follow the steps from [this](https://github.com/shipwright-io/build?tab=readme-ov-file#try-it) section until you create the push secret.
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +And one can find the list of vulnerabilities in the build run status.Output
```suggestion
And one can find the list of vulnerabilities in the build run under the `.status.output`path:
```

2024-07-16 07:18 UTC, qu1queee commented on content/en/blog/posts/2024-07-15-vulnerability-scanning.md
> +Shipwright offers a robust and flexible solution for building container images within Kubernetes environments. By integrating vulnerability scanning directly into the build process, Shipwright ensure
```suggestion
Shipwright offers a robust and flexible solution for building container images within Kubernetes environments. By integrating vulnerability scanning directly into the build process, Shipwright ensures that container images are secure and compliant with Industry Standards and gets closer to Supply Chain Security Best Practices.
```

2024-07-16 10:18 UTC, qu1queee approved these changes
/lgtm
/approve

2024-07-16 10:21 UTC, merged