Import documentation
shipwright-io/website pull request #27
Opened 2021-03-16 20:32 UTC by sftim

A quick PR to import documentation from https://github.com/shipwright-io/build/tree/master/docs

2021-03-16 20:32 UTC, sftim commented
@adambkaplan thoughts?

2021-03-16 20:33 UTC, sftim commented
/kind documentation

2021-03-17 07:07 UTC, zhangtbj commented
Can we just link the document from `shipwright/build` directly instead copy and store a copy in the website repo?

I think they are duplicates and we have to update/maintain them if there is any update on the shipwright/build side (I think it will happen frequently this year.)

2021-03-17 16:04 UTC, adambkaplan commented
> Can we just link the document from shipwright/build directly instead copy and store a copy in the website repo?
> 
> I think they are duplicates and we have to update/maintain them if there is any update on the shipwright/build side (I think it will happen frequently this year.)

@zhangtbj I share your concern about having duplicate docs. shipwright.io is our user-facing website, therefore user-facing documentation should live there long term.

We can flip our contributing guide and ask new features to have PRs opened against shipwright-io/website. Upstream Kubernetes is large enough that a dedicated SIG tracks features and helps draft docs [1]. At our state is to too much to ask developers to draft feature docs?

[1] https://kubernetes.io/docs/contribute/new-content/new-features/

2021-03-17 16:27 UTC, adambkaplan requested changes
@sftim thank you for the PR!

I noticed that the api docs don't generate their own sub-level in the sidebar, so for now everything is under one level. I think if you add `_index.md` files in the subfolders, we get those sub-headers for free?

Regarding segments, I think for this initial import we can split into two:

1. "Concepts"
2. "Configuration"

The latter exposes a lot of fine tuning that a new Shipwright user would not necessarily use.

P.S. miss you from sig-docs, as you can see I've been busy lately :wave:.

2021-03-17 16:27 UTC, adambkaplan commented on content/en/docs/_index.md
>  linkTitle: "Documentation"
Note to self - the imported article is a true overview. In the long term we will want this page to serve as a table of contents, so keeping the "Documentation" title is appropriate.

2021-03-17 16:27 UTC, adambkaplan commented on content/en/docs/api/build.md
> +title: Build
Can you rename the folder "concepts" instead of "api"?

2021-03-17 16:27 UTC, adambkaplan commented on content/en/docs/authentication.md
> +title: Authentication during builds
I think this too can live under "concepts"

2021-03-17 16:27 UTC, adambkaplan commented on content/en/docs/controller_flow.md
> +The following image illustrate the interactions between the Build, BuildRun controller and the Tekton Pipeline controller:
This is a bit more of an architecture article, and not meant for end users. For now I say it can live in shipwright-io/build

2021-03-17 16:27 UTC, adambkaplan commented on content/en/docs/metrics.md
> +title: Build Controller Metrics
Note that this is geared towards installation/configuration of the controller. More is coming in this regard as we are tuning our installation process.

2021-03-17 16:27 UTC, adambkaplan commented on content/en/docs/profiling.md
> +title: Build Controller Profiling
Likewise, this is an install/configuration article.

2021-03-17 16:27 UTC, adambkaplan commented on content/en/docs/configuration.md
> +title: "Configuration"
This is an install/configuration article

2021-03-17 17:43 UTC, sftim commented
> I noticed that the api docs don't generate their own sub-level in the sidebar, so for now everything is under one level. I think if you add `_index.md` files in the subfolders, we get those sub-headers for free?

Indeed. I was hoping another contributor would be willing to add an API overview - maybe after this merges? I know there's room for further tidying but as Voltaire never quite said, “the perfect is the enemy of the deployed”.

2021-03-17 18:23 UTC, adambkaplan commented
> Indeed. I was hoping another contributor would be willing to add an API overview - maybe after this merges? I know there's room for further tidying but as Voltaire never quite said, “the perfect is the enemy of the deployed”.

Agree. We've also highlighted a path to organizing the docs in #24 - this import gives us something real to iterate on.

2021-03-18 12:41 UTC, adambkaplan approved these changes
/approve

Added spelling correction.

2021-03-18 12:41 UTC, adambkaplan commented on content/en/docs/api/build.md
> +title: Build
Sounds good.

2021-03-23 12:44 UTC, adambkaplan commented
@sftim in Monday's call, the community expressed strong desire for keeping documentation closer to the code repositories (ex - github.com/shipwright-io/build), and syncing that content here. Tekton has an interesting script that facilitates this process [1].

@zhangtbj @qu1queee @gabemontero I'd like to propose the following (will also send this to the dev mailing list):

1. Merge this PR so we have a base level of content to work with.
2. Update the folder structure and file front matter in `website` so the docs are structured and presented to our liking.
3. Add the appropriate front matter to the docs in `build`
4. Incorporate the Tekton sync script (with adjustments as needed) into `website`.

[1] https://github.com/tektoncd/website/tree/main/sync

2021-03-23 12:46 UTC, gabemontero commented
+1 @adambkaplan

2021-03-23 12:58 UTC, sftim commented
We can fetch the content over from https://github.com/shipwright-io/build during a build of this repo, so that this repo doesn't hold a synced copy but it still previews OK locally, on Netlify, and publishes how we expect.

BTW what we lose there is CI/CD: how do we ensure that a documentation change to https://github.com/shipwright-io/build is valid?
We don't have that now so there's no regression.

2021-03-23 13:26 UTC, adambkaplan commented
> BTW what we lose there is CI/CD: how do we ensure that a documentation change to https://github.com/shipwright-io/build is valid?
> We don't have that now so there's no regression.

I think we can take a near term/long term strategy here

Near term: keep a synced copy in git, update via pull requests.
Medium term: Add a "docs" GitHub action in shipwright-io/build (and future repositories) which checks out the website code, runs the sync, and then has hugo generate the static content.  Failures here will need to have clear messaging so contributors know what went wrong and how to fix it.
Long term: Stop syncing content to git, switch to nightly deployments.

My hope is that with the docs GitHub action, we will catch 90% of bugs that would cause the Netlify deployment to fail from synced content.

2021-03-24 02:48 UTC, zhangtbj commented
+1, thanks!

2021-03-24 15:31 UTC, adambkaplan commented
/lgtm

2021-03-24 15:32 UTC, merged