Add gatekeeper blog post
shipwright-io/website pull request #49
Opened 2021-08-02 19:25 UTC by blairdrummond

Based on feedback [here](https://github.com/shipwright-io/build/pull/845#issuecomment-891169979), repackaging a `docs` PR as a blog-post on how to configure an Allowlist on source urls using a Gatekeeper constraint.

Cheers, and let me know if you have any feedback!

2021-08-08 16:54 UTC, gabemontero requested changes
Just a couple of minor suggestions wrt vendor neutrality @blairdrummond 

thanks

2021-08-08 16:54 UTC, gabemontero commented on content/en/blog/posts/2021-08-02-adding-gatekeeper.md/index.md
> +Unless you are using a tool like [source-to-image](https://github.com/openshift/source-to-image) to build images without root, there are risks to building arbitrary Docker images within your cluster.
In the interest of vendor neutrality, please replace `Docker images` with `Open Container Initiative container images`, like one sees with https://github.com/containers/buildah#buildah---a-tool-that-facilitates-building-open-container-initiative-oci-container-images

2021-08-08 16:54 UTC, gabemontero commented on content/en/blog/posts/2021-08-02-adding-gatekeeper.md/index.md
> +Unless you are using a tool like [source-to-image](https://github.com/openshift/source-to-image) to build images without root, there are risks to building arbitrary Docker images within your cluster.
Also, source to image I do not believe is the only build tool with the ability to produce images with non-root.  Or at minimum, it is an evolving space.  How about we just say "Unless you are able to build images without root privileges, ..."

2021-08-09 16:31 UTC, gabemontero commented
/lgtm

/assign @sbose78 

for the approve label, or to pull in other folks to take a look before merging

2021-08-16 15:24 UTC, adambkaplan approved these changes
/approve

This is an awesome blog post. I love everything about it. Thank you @blairdrummond

2021-08-16 15:25 UTC, merged